# Generated by Django 5.0.4 on 2024-05-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_agence', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('matricule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=15)),
                ('matricule', models.CharField(editable=False, max_length=100)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localpayment.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localpayment.client')),
                ('type_lavage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localpayment.typel')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localpayment.vendeur')),
            ],
        ),
    ]
