# Generated by Django 5.0.4 on 2024-05-13 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
