# Generated by Django 5.0.4 on 2024-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0002_vendeur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
