# Generated by Django 5.0.4 on 2024-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0003_alter_ticket_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
