# Generated by Django 5.0.4 on 2024-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0005_alter_ticket_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
