# Generated by Django 5.0.4 on 2024-05-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0007_user_ticket_est_utilise_alter_ticket_vendeur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
