# Generated by Django 5.0.4 on 2024-05-31 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpayment', '0008_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agence',
        ),
        migrations.DeleteModel(
            name='TypeL',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Agence',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
