# Generated by Django 5.0.4 on 2024-05-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='adresse email')),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('numero_telephone', models.CharField(max_length=15, unique=True)),
                ('ville_residence', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lavage',
            fields=[
                ('codeQR', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('numero_compte', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailApp.utilisateur')),
            ],
        ),
    ]
