# Generated by Django 5.0.4 on 2024-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
