# Generated by Django 5.1.8 on 2026-07-25 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0003_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numero_compte',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ReservationHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passage', models.DateField()),
                ('heure_passage', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lavage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='emailApp.lavage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_passage', 'heure_passage'],
                'unique_together': {('date_passage', 'heure_passage')},
            },
        ),
    ]
